'use client'
import { API } from "@/api/api";
import { ChangeEvent, useEffect, useState } from "react";
import Posts from "@/components/Posts";
import SearchPost from "@/components/SearchPost";
//import { Metadata } from "next";

export type PostType = {
  userId: number
  id: number
  title: string
  body: string
}
// export const metadata: Metadata = {
//   title: "Blog | V_App",
//   description: "Generated by create next app"
// };

function Blog() {
  const [posts, setPosts] = useState<PostType[]>([]);
  const [searchedValue, setSearchedValue] = useState('');
  const [loading, setLoading] = useState(true)
  useEffect(() => {
    API.getPosts()
      .then((res) => setPosts(res)) // .then(setPosts)
      .finally(() => setLoading(false))
  }, []);

  const filteredPosts: PostType[] = posts.filter((post: PostType) => {
    return post.title.indexOf(`${searchedValue}`) > -1 && post;
  });

  return (
    <>
      <div>Blog page</div>
      <SearchPost value={searchedValue} setSearchedValue={setSearchedValue} />
      {loading ? <h3>Loading ...</h3> : <Posts posts={filteredPosts} />}
    </>
  );
}

export default Blog;