import type {Metadata} from "next";
import Link from "next/link";
import {API} from "@/api/api";

export const metadata: Metadata = {
    title: "Blog | V_App",
    description: "Generated by create next app",
};

async function Blog() {
    const posts = await API.getPosts()
    return (
        <>
            <div>Blog page</div>
            <ul>
                {posts.map((post: any) => (
                    <li key={post.id}>
                        <Link href={`/blog/${post.id}`}>{post.title}</Link>
                    </li>))}
            </ul>
        </>
    );
}

export default Blog;