import React from 'react';
import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "About | V_app",
    description: "Generated by create next app",
};
function About() {
    return (
        <h2>About page</h2>
    );
}

export default About;