import React from "react";
import type { Metadata } from "next";
import "./null.css";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "V_App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className='wrapper'>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
